<?php
declare(strict_types=1);

namespace Figuren_Theater\FeaturesRepo;

use Figuren_Theater\inc\EventManager;

use Figuren_Theater\Network\Features;


class Feature__wordpress_in_bestform extends Features\Feature__Abstract implements EventManager\SubscriberInterface
{

	const SLUG = 'wordpress-in-bestform';


	/**
	 * Returns an array of hooks that this subscriber wants to register with
	 * the WordPress plugin API.
	 *
	 * @return array
	 */
	public static function get_subscribed_events() : array
	{
		return array(
			'template_redirect' => 'remove_admin_bar_for_foreign_users',
			'admin_bar_menu' => [ 'remove_from_admin_bar', 999 ],

		);
	}

	public function enable() : void {}
 
	public static function remove_admin_bar_for_foreign_users() {

		// Removes the Admin Bar
		if ( ! \is_user_logged_in() )
			return;

		// is current user
		// a member of
		// current site
		$_sites_of_current_user = \get_blogs_of_user( \get_current_user_id() );
		$_current_blog_id       = \get_current_blog_id();
		if ( ! array_key_exists( $_current_blog_id, $_sites_of_current_user ) ) {
			// phpcs:ignore WordPressVIPMinimum.UserExperience.AdminBarRemoval.RemovalDetected
			\show_admin_bar( false );
		}
	}


	public function remove_from_admin_bar( $wp_admin_bar ) {
		
		$wp_admin_bar->remove_node( 'customize' );
		

		if ( \current_user_can( 'manage_sites' ) )
			return;
	 
		/*
		 * Items placed outside the if statement will remove it from both the frontend
		 * and backend of the site
		*/
		$wp_admin_bar->remove_node( 'my-sites' );
		$wp_admin_bar->remove_node( 'themes' );

		/*
wp_die('<pre>'.var_export([
	$wp_admin_bar,
],true).'</pre>');
*/
		/*
		 * Placing items in here will only remove them from admin bar
		 * when viewing the fronte end of the site
		if ( ! is_admin() ) {
			// Example of removing item generated by plugin. Full ID is #wp-admin-bar-si_menu
			$wp_admin_bar->remove_node('si_menu');
	 
			// WordPress Core Items (uncomment to remove)
			$wp_admin_bar->remove_node('updates');
			$wp_admin_bar->remove_node('comments');
			$wp_admin_bar->remove_node('new-content');
			//$wp_admin_bar->remove_node('wp-logo');
			//$wp_admin_bar->remove_node('site-name');
			//$wp_admin_bar->remove_node('my-account');
			//$wp_admin_bar->remove_node('search');
		}
		*/

	}

}
// NO NEED TO CALL THIS CLASS DIRECTLY
// our 'Bootstrap_FeaturesRepo' Class takes care of it
// as long as this file lives in the \FeaturesRepo ;)
